# coding=utf-8

# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\WorkSpace\Pyqt5_eric6\hello_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import *
from day12 import main

# 继承QWidget
class TableWidget(QWidget):
    # customer_list = [("张三", "男", "1981-06-02", "13888888888",
    #                   "南极路企鹅临舍傍9号999路"),
    #                  ("李四", "男", "1988-08-08", "13999999999",
    #                   "北极熊店的下坡路中6号666路"),
    #                  ("李清照", "女", "1986-06-06", "13666666666",
    #                   "秦岭古诗庙湾道8号888路")]
    customer_list = main()
    table_widget = None

    def __init__(self):
        super().__init__()
        self.init_ui()


    def init_ui(self):
        # 设置布局
        layout = QHBoxLayout()
        # 数据层次结构，10行5列
        self.table_widget = QTableWidget(2000, 7)
        # 输入内容
        for (row, customer) in enumerate(self.customer_list):
            for column in range(len(customer)):

                self.table_widget.setItem(
                    row, column, QTableWidgetItem(
                        str(customer[column])))
        self.table_widget.resizeColumnToContents(0)
        self.table_widget.resizeColumnToContents(1)
        self.table_widget.resizeColumnToContents(2)
        self.table_widget.resizeColumnToContents(3)
        self.table_widget.resizeColumnToContents(4)
        self.table_widget.resizeColumnToContents(5)
        self.table_widget.resizeColumnToContents(6)

        layout.addWidget(self.table_widget)

        # 选择单行
        self.table_widget.setSelectionBehavior(QAbstractItemView
                                               .SelectRows)
        # # 单击事件
        # self.table_widget.cellClicked.connect(self.table_click)
        # 双击事件
        # self.table_widget.cellDoubleClicked.connect(self.double_click)

        self.setLayout(layout)
        # 内容修改
        self.table_widget.cellChanged.connect(self.wordchange)


        # 调整窗口大小
        # self.resize(900, 500)
        # 窗口居中

        # 窗口标题
        self.setWindowTitle("QTableWidget应用")
        # 显示窗口
        self.show()

    def wordchange(self):
         data=self.table_widget.currentItem()
         print(data.text())
         # print(data.text())

    # def double_click(self):
    #     # 选中行
    #     data = self.table_widget.currentItem()
    #
    #     print("选中单元格的数据:%s" % data.text())

    # 实现居中

if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = TableWidget()
    sys.exit(app.exec_())
